# Generated by Django 4.1 on 2022-09-05 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=50, verbose_name='Nombre del personaje')),
                ('username', models.CharField(max_length=254, unique=True, verbose_name='username')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20, verbose_name='Nombre del movimiento')),
                ('combination', models.CharField(max_length=6, verbose_name='combination')),
                ('energy', models.IntegerField(verbose_name='Energía que quita')),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='players.player')),
            ],
            options={
                'verbose_name': 'Power',
                'verbose_name_plural': 'Powers',
            },
        ),
    ]
